const ActionTypes = {
  START_GET_DATA: 'START_GET_DATA',
  DONE_GET_DATA: 'DONE_GET_DATA',
  MQTT_MESSAGE_ARRIVED: 'MQTT_MESSAGE_ARRIVED',
  MQTT_CONNECTING: 'MQTT_CONNECTING',
  MQTT_CONNECTION_SUCCESS: 'MQTT_CONNECTION_SUCCESS'
}

export default ActionTypes